DROP TABLE IF EXISTS connection;
CREATE TABLE connection(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  host VARCHAR NOT NULL, 
  port INT NOT NULL, 
  username VARCHAR NOT NULL, 
  userpw VARCHAR NOT NULL, 
  base VARCHAR NOT NULL);